### ISSUE TITLE
Question: Stated browser support

### ISSUE THREAD

**Issue by JakeChampion** [fastly/performance-observer-polyfill#3]
Hi,

Do you know which browsers this polyfill supports and whether this polyfill has been tested in those browsers?

Thanks in advance for any help,
Jake

**Comment by tedconn** [comment]
The documentation says::

> Therefore the polyfill can only be used to observe the entry types: navigation, resource and mark.

Which makes sense if you look at the support for each of the individual [entryTypes](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceEntry)
